# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test', '0003_auto_20180118_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test.Complexity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='resultquestion',
            name='attempt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
