# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_auto_20180118_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
